#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HomeControl.Resource", IsApplication=true)]

namespace HomeControl
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int ambientEnabled = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int buttonSize = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int cameraBearing = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int cameraMaxZoomPreference = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int cameraMinZoomPreference = 2130771972;
			
			// aapt resource value: 0x7F010005
			public const int cameraTargetLat = 2130771973;
			
			// aapt resource value: 0x7F010006
			public const int cameraTargetLng = 2130771974;
			
			// aapt resource value: 0x7F010007
			public const int cameraTilt = 2130771975;
			
			// aapt resource value: 0x7F010008
			public const int cameraZoom = 2130771976;
			
			// aapt resource value: 0x7F010009
			public const int circleCrop = 2130771977;
			
			// aapt resource value: 0x7F01000A
			public const int colorScheme = 2130771978;
			
			// aapt resource value: 0x7F01000B
			public const int font = 2130771979;
			
			// aapt resource value: 0x7F01000C
			public const int fontProviderAuthority = 2130771980;
			
			// aapt resource value: 0x7F01000D
			public const int fontProviderCerts = 2130771981;
			
			// aapt resource value: 0x7F01000E
			public const int fontProviderFetchStrategy = 2130771982;
			
			// aapt resource value: 0x7F01000F
			public const int fontProviderFetchTimeout = 2130771983;
			
			// aapt resource value: 0x7F010010
			public const int fontProviderPackage = 2130771984;
			
			// aapt resource value: 0x7F010011
			public const int fontProviderQuery = 2130771985;
			
			// aapt resource value: 0x7F010012
			public const int fontStyle = 2130771986;
			
			// aapt resource value: 0x7F010013
			public const int fontWeight = 2130771987;
			
			// aapt resource value: 0x7F010014
			public const int imageAspectRatio = 2130771988;
			
			// aapt resource value: 0x7F010015
			public const int imageAspectRatioAdjust = 2130771989;
			
			// aapt resource value: 0x7F010016
			public const int latLngBoundsNorthEastLatitude = 2130771990;
			
			// aapt resource value: 0x7F010017
			public const int latLngBoundsNorthEastLongitude = 2130771991;
			
			// aapt resource value: 0x7F010018
			public const int latLngBoundsSouthWestLatitude = 2130771992;
			
			// aapt resource value: 0x7F010019
			public const int latLngBoundsSouthWestLongitude = 2130771993;
			
			// aapt resource value: 0x7F01001A
			public const int liteMode = 2130771994;
			
			// aapt resource value: 0x7F01001B
			public const int mapType = 2130771995;
			
			// aapt resource value: 0x7F01001C
			public const int scopeUris = 2130771996;
			
			// aapt resource value: 0x7F01001D
			public const int uiCompass = 2130771997;
			
			// aapt resource value: 0x7F01001E
			public const int uiMapToolbar = 2130771998;
			
			// aapt resource value: 0x7F01001F
			public const int uiRotateGestures = 2130771999;
			
			// aapt resource value: 0x7F010020
			public const int uiScrollGestures = 2130772000;
			
			// aapt resource value: 0x7F010021
			public const int uiTiltGestures = 2130772001;
			
			// aapt resource value: 0x7F010022
			public const int uiZoomControls = 2130772002;
			
			// aapt resource value: 0x7F010023
			public const int uiZoomGestures = 2130772003;
			
			// aapt resource value: 0x7F010024
			public const int useViewLifecycle = 2130772004;
			
			// aapt resource value: 0x7F010025
			public const int zOrderOnTop = 2130772005;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7F020000
			public const int abc_action_bar_embed_tabs = 2130837504;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int common_google_signin_btn_text_dark = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int common_google_signin_btn_text_dark_default = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int common_google_signin_btn_text_dark_disabled = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int common_google_signin_btn_text_dark_focused = 2130903043;
			
			// aapt resource value: 0x7F030004
			public const int common_google_signin_btn_text_dark_pressed = 2130903044;
			
			// aapt resource value: 0x7F030005
			public const int common_google_signin_btn_text_light = 2130903045;
			
			// aapt resource value: 0x7F030006
			public const int common_google_signin_btn_text_light_default = 2130903046;
			
			// aapt resource value: 0x7F030007
			public const int common_google_signin_btn_text_light_disabled = 2130903047;
			
			// aapt resource value: 0x7F030008
			public const int common_google_signin_btn_text_light_focused = 2130903048;
			
			// aapt resource value: 0x7F030009
			public const int common_google_signin_btn_text_light_pressed = 2130903049;
			
			// aapt resource value: 0x7F03000A
			public const int common_google_signin_btn_tint = 2130903050;
			
			// aapt resource value: 0x7F03000B
			public const int notification_action_color_filter = 2130903051;
			
			// aapt resource value: 0x7F03000C
			public const int notification_icon_bg_color = 2130903052;
			
			// aapt resource value: 0x7F03000D
			public const int notification_material_background_media_default_color = 2130903053;
			
			// aapt resource value: 0x7F03000E
			public const int primary_text_default_material_dark = 2130903054;
			
			// aapt resource value: 0x7F03000F
			public const int ripple_material_light = 2130903055;
			
			// aapt resource value: 0x7F030010
			public const int secondary_text_default_material_dark = 2130903056;
			
			// aapt resource value: 0x7F030011
			public const int secondary_text_default_material_light = 2130903057;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F040000
			public const int compat_button_inset_horizontal_material = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int compat_button_inset_vertical_material = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int compat_button_padding_horizontal_material = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int compat_button_padding_vertical_material = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int compat_control_corner_material = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int notification_action_icon_size = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int notification_action_text_size = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int notification_big_circle_margin = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int notification_content_margin_start = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int notification_large_icon_height = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int notification_large_icon_width = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int notification_main_column_padding_top = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int notification_media_narrow_margin = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int notification_right_icon_size = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int notification_right_side_padding_top = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int notification_small_icon_background_padding = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int notification_small_icon_size_as_large = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int notification_subtext_size = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notification_top_pad = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int notification_top_pad_large_text = 2130968595;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F050000
			public const int common_full_open_on_phone = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int common_google_signin_btn_icon_dark = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int common_google_signin_btn_icon_dark_focused = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int common_google_signin_btn_icon_dark_normal = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int common_google_signin_btn_icon_dark_normal_background = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int common_google_signin_btn_icon_disabled = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int common_google_signin_btn_icon_light = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int common_google_signin_btn_icon_light_focused = 2131034119;
			
			// aapt resource value: 0x7F050008
			public const int common_google_signin_btn_icon_light_normal = 2131034120;
			
			// aapt resource value: 0x7F050009
			public const int common_google_signin_btn_icon_light_normal_background = 2131034121;
			
			// aapt resource value: 0x7F05000A
			public const int common_google_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7F05000B
			public const int common_google_signin_btn_text_dark_focused = 2131034123;
			
			// aapt resource value: 0x7F05000C
			public const int common_google_signin_btn_text_dark_normal = 2131034124;
			
			// aapt resource value: 0x7F05000D
			public const int common_google_signin_btn_text_dark_normal_background = 2131034125;
			
			// aapt resource value: 0x7F05000E
			public const int common_google_signin_btn_text_disabled = 2131034126;
			
			// aapt resource value: 0x7F05000F
			public const int common_google_signin_btn_text_light = 2131034127;
			
			// aapt resource value: 0x7F050010
			public const int common_google_signin_btn_text_light_focused = 2131034128;
			
			// aapt resource value: 0x7F050011
			public const int common_google_signin_btn_text_light_normal = 2131034129;
			
			// aapt resource value: 0x7F050012
			public const int common_google_signin_btn_text_light_normal_background = 2131034130;
			
			// aapt resource value: 0x7F050013
			public const int googleg_disabled_color_18 = 2131034131;
			
			// aapt resource value: 0x7F050014
			public const int googleg_standard_color_18 = 2131034132;
			
			// aapt resource value: 0x7F050015
			public const int Icon = 2131034133;
			
			// aapt resource value: 0x7F050016
			public const int notification_action_background = 2131034134;
			
			// aapt resource value: 0x7F050017
			public const int notification_bg = 2131034135;
			
			// aapt resource value: 0x7F050018
			public const int notification_bg_low = 2131034136;
			
			// aapt resource value: 0x7F050019
			public const int notification_bg_low_normal = 2131034137;
			
			// aapt resource value: 0x7F05001A
			public const int notification_bg_low_pressed = 2131034138;
			
			// aapt resource value: 0x7F05001B
			public const int notification_bg_normal = 2131034139;
			
			// aapt resource value: 0x7F05001C
			public const int notification_bg_normal_pressed = 2131034140;
			
			// aapt resource value: 0x7F05001D
			public const int notification_icon_background = 2131034141;
			
			// aapt resource value: 0x7F05001E
			public const int notification_template_icon_bg = 2131034142;
			
			// aapt resource value: 0x7F05001F
			public const int notification_template_icon_low_bg = 2131034143;
			
			// aapt resource value: 0x7F050020
			public const int notification_tile_bg = 2131034144;
			
			// aapt resource value: 0x7F050021
			public const int notify_panel_notification_icon_bg = 2131034145;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F060000
			public const int action0 = 2131099648;
			
			// aapt resource value: 0x7F060005
			public const int actions = 2131099653;
			
			// aapt resource value: 0x7F060001
			public const int action_container = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int action_divider = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int action_image = 2131099651;
			
			// aapt resource value: 0x7F060004
			public const int action_text = 2131099652;
			
			// aapt resource value: 0x7F060006
			public const int adjust_height = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int adjust_width = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int async = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int auto = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int blocking = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int cancel_action = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int chronometer = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int dark = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int end_padder = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int forever = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int gridView = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int hybrid = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int icon = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int icon_group = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int icon_only = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int info = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int italic = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int light = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int line1 = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int line3 = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int media_actions = 2131099674;
			
			// aapt resource value: 0x7F06001B
			public const int none = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int normal = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int notification_background = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int notification_main_column = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int notification_main_column_container = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int right_icon = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int right_side = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int satellite = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int setTemperature = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int standard = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int status_bar_latest_event_content = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int temperatureDown = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int temperatureUp = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int terrain = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int text = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int text2 = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int textName = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int textTemperature = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int time = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int title = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int wide = 2131099695;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7F070000
			public const int cancel_button_image_alpha = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int google_play_services_version = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int status_bar_notification_info_maxnum = 2131165186;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F080000
			public const int ChangeTemperature = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int Main = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int notification_action = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int notification_action_tombstone = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int notification_media_action = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int notification_media_cancel_action = 2131230725;
			
			// aapt resource value: 0x7F080006
			public const int notification_template_big_media = 2131230726;
			
			// aapt resource value: 0x7F080007
			public const int notification_template_big_media_custom = 2131230727;
			
			// aapt resource value: 0x7F080008
			public const int notification_template_big_media_narrow = 2131230728;
			
			// aapt resource value: 0x7F080009
			public const int notification_template_big_media_narrow_custom = 2131230729;
			
			// aapt resource value: 0x7F08000A
			public const int notification_template_custom_big = 2131230730;
			
			// aapt resource value: 0x7F08000B
			public const int notification_template_icon_group = 2131230731;
			
			// aapt resource value: 0x7F08000C
			public const int notification_template_lines_media = 2131230732;
			
			// aapt resource value: 0x7F08000D
			public const int notification_template_media = 2131230733;
			
			// aapt resource value: 0x7F08000E
			public const int notification_template_media_custom = 2131230734;
			
			// aapt resource value: 0x7F08000F
			public const int notification_template_part_chronometer = 2131230735;
			
			// aapt resource value: 0x7F080010
			public const int notification_template_part_time = 2131230736;
			
			// aapt resource value: 0x7F080011
			public const int TemperatureItem = 2131230737;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F090000
			public const int ApplicationName = 2131296256;
			
			// aapt resource value: 0x7F090002
			public const int common_google_play_services_enable_button = 2131296258;
			
			// aapt resource value: 0x7F090003
			public const int common_google_play_services_enable_text = 2131296259;
			
			// aapt resource value: 0x7F090004
			public const int common_google_play_services_enable_title = 2131296260;
			
			// aapt resource value: 0x7F090005
			public const int common_google_play_services_install_button = 2131296261;
			
			// aapt resource value: 0x7F090006
			public const int common_google_play_services_install_text = 2131296262;
			
			// aapt resource value: 0x7F090007
			public const int common_google_play_services_install_title = 2131296263;
			
			// aapt resource value: 0x7F090008
			public const int common_google_play_services_notification_ticker = 2131296264;
			
			// aapt resource value: 0x7F090009
			public const int common_google_play_services_unknown_issue = 2131296265;
			
			// aapt resource value: 0x7F09000A
			public const int common_google_play_services_unsupported_text = 2131296266;
			
			// aapt resource value: 0x7F09000B
			public const int common_google_play_services_update_button = 2131296267;
			
			// aapt resource value: 0x7F09000C
			public const int common_google_play_services_update_text = 2131296268;
			
			// aapt resource value: 0x7F09000D
			public const int common_google_play_services_update_title = 2131296269;
			
			// aapt resource value: 0x7F09000E
			public const int common_google_play_services_updating_text = 2131296270;
			
			// aapt resource value: 0x7F09000F
			public const int common_google_play_services_wear_update_text = 2131296271;
			
			// aapt resource value: 0x7F090010
			public const int common_open_on_phone = 2131296272;
			
			// aapt resource value: 0x7F090011
			public const int common_signin_button_text = 2131296273;
			
			// aapt resource value: 0x7F090012
			public const int common_signin_button_text_long = 2131296274;
			
			// aapt resource value: 0x7F090001
			public const int Hello = 2131296257;
			
			// aapt resource value: 0x7F090013
			public const int status_bar_notification_info_overflow = 2131296275;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F0A0000
			public const int TextAppearance_Compat_Notification = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int TextAppearance_Compat_Notification_Info = 2131361793;
			
			// aapt resource value: 0x7F0A0002
			public const int TextAppearance_Compat_Notification_Info_Media = 2131361794;
			
			// aapt resource value: 0x7F0A0003
			public const int TextAppearance_Compat_Notification_Line2 = 2131361795;
			
			// aapt resource value: 0x7F0A0004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2131361796;
			
			// aapt resource value: 0x7F0A0005
			public const int TextAppearance_Compat_Notification_Media = 2131361797;
			
			// aapt resource value: 0x7F0A0006
			public const int TextAppearance_Compat_Notification_Time = 2131361798;
			
			// aapt resource value: 0x7F0A0007
			public const int TextAppearance_Compat_Notification_Time_Media = 2131361799;
			
			// aapt resource value: 0x7F0A0008
			public const int TextAppearance_Compat_Notification_Title = 2131361800;
			
			// aapt resource value: 0x7F0A0009
			public const int TextAppearance_Compat_Notification_Title_Media = 2131361801;
			
			// aapt resource value: 0x7F0A000A
			public const int Widget_Compat_NotificationActionContainer = 2131361802;
			
			// aapt resource value: 0x7F0A000B
			public const int Widget_Compat_NotificationActionText = 2131361803;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F01000C,0x7F01000D,0x7F01000E,0x7F01000F,0x7F010010,0x7F010011 }
			public static int[] FontFamily = new int[] {
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985};
			
			// aapt resource value: { 0x7F01000B,0x7F010012,0x7F010013 }
			public static int[] FontFamilyFont = new int[] {
					2130771979,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int FontFamilyFont_font = 0;
			
			// aapt resource value: 1
			public const int FontFamilyFont_fontStyle = 1;
			
			// aapt resource value: 2
			public const int FontFamilyFont_fontWeight = 2;
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderCerts = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderFetchStrategy = 2;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderFetchTimeout = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderPackage = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderQuery = 5;
			
			// aapt resource value: { 0x7F010009,0x7F010014,0x7F010015 }
			public static int[] LoadingImageView = new int[] {
					2130771977,
					2130771988,
					2130771989};
			
			// aapt resource value: 0
			public const int LoadingImageView_circleCrop = 0;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 2
			public const int LoadingImageView_imageAspectRatioAdjust = 2;
			
			// aapt resource value: { 0x7F010000,0x7F010002,0x7F010003,0x7F010004,0x7F010005,0x7F010006,0x7F010007,0x7F010008,0x7F010016,0x7F010017,0x7F010018,0x7F010019,0x7F01001A,0x7F01001B,0x7F01001D,0x7F01001E,0x7F01001F,0x7F010020,0x7F010021,0x7F010022,0x7F010023,0x7F010024,0x7F010025 }
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005};
			
			// aapt resource value: 0
			public const int MapAttrs_ambientEnabled = 0;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraMaxZoomPreference = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraMinZoomPreference = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTargetLat = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraTargetLng = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_cameraTilt = 6;
			
			// aapt resource value: 7
			public const int MapAttrs_cameraZoom = 7;
			
			// aapt resource value: 8
			public const int MapAttrs_latLngBoundsNorthEastLatitude = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_latLngBoundsNorthEastLongitude = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_latLngBoundsSouthWestLatitude = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_latLngBoundsSouthWestLongitude = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_liteMode = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_mapType = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_uiCompass = 14;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 16
			public const int MapAttrs_uiRotateGestures = 16;
			
			// aapt resource value: 17
			public const int MapAttrs_uiScrollGestures = 17;
			
			// aapt resource value: 18
			public const int MapAttrs_uiTiltGestures = 18;
			
			// aapt resource value: 19
			public const int MapAttrs_uiZoomControls = 19;
			
			// aapt resource value: 20
			public const int MapAttrs_uiZoomGestures = 20;
			
			// aapt resource value: 21
			public const int MapAttrs_useViewLifecycle = 21;
			
			// aapt resource value: 22
			public const int MapAttrs_zOrderOnTop = 22;
			
			// aapt resource value: { 0x7F010001,0x7F01000A,0x7F01001C }
			public static int[] SignInButton = new int[] {
					2130771969,
					2130771978,
					2130771996};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
